global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'product-catalog'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-catalog:8080']
