CREATE TABLE product
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    description       VARCHAR(255),
    price             DECIMAL,
    category          VARCHAR(255),
    stock             INT,
    created_date      TIMESTAMP,
    last_updated_date TIMESTAMP,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

INSERT INTO product (name, description, price, category, stock, created_date, last_updated_date) VALUES
                                                                                                     ('Product 1', 'Description 1', 100.00, 'Category A', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                     ('Product 2', 'Description 2', 200.00, 'Category A', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                     ('Product 3', 'Description 3', 300.00, 'Category B', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE INDEX idx_product_category ON product (category);
CREATE INDEX idx_product_name ON product (name);

